#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Mar 31 01:47:04 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=4
shaderPack=Sildur's Vibrant Shaders v1.51 Medium.zip
